package oracle.fod.storefront.module;

import oracle.fod.storefront.module.common.FODCheckoutAM;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 18 21:19:44 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FODCheckoutAMImpl extends BaseApplicationModuleImpl implements FODCheckoutAM {
    /**
     * This is the default constructor (do not remove).
     */
    public FODCheckoutAMImpl() {
    }

    /**
     * Container's getter for ShoppingCart1.
     * @return ShoppingCart1
     */
    public ViewObjectImpl getShoppingCart1() {
        return (ViewObjectImpl) findViewObject("ShoppingCart1");
    }

    /**
     * Container's getter for ShoppingCartItem1.
     * @return ShoppingCartItem1
     */
    public ViewObjectImpl getShoppingCartItem1() {
        return (ViewObjectImpl) findViewObject("ShoppingCartItem1");
    }

    /**
     * Container's getter for ShippingAddress.
     * @return ShippingAddress
     */
    public ViewObjectImpl getShippingAddress() {
        return (ViewObjectImpl) findViewObject("ShippingAddress");
    }

    /**
     * Container's getter for PaymentOptionV1.
     * @return PaymentOptionV1
     */
    public ViewObjectImpl getPaymentOptionV1() {
        return (ViewObjectImpl) findViewObject("PaymentOptionV1");
    }

    /**
     * Container's getter for BillToAddress.
     * @return BillToAddress
     */
    public ViewObjectImpl getBillToAddress() {
        return (ViewObjectImpl) findViewObject("BillToAddress");
    }

    /**
     * Container's getter for OrderItemsOrdersFkLink1.
     * @return OrderItemsOrdersFkLink1
     */
    public ViewLinkImpl getOrderItemsOrdersFkLink1() {
        return (ViewLinkImpl) findViewLink("OrderItemsOrdersFkLink1");
    }

    /**
     * Container's getter for ShoppingCartAddressLink1.
     * @return ShoppingCartAddressLink1
     */
    public ViewLinkImpl getShoppingCartAddressLink1() {
        return (ViewLinkImpl) findViewLink("ShoppingCartAddressLink1");
    }

    /**
     * Container's getter for ShoppingCartPaymentOptionViewLink1.
     * @return ShoppingCartPaymentOptionViewLink1
     */
    public ViewLinkImpl getShoppingCartPaymentOptionViewLink1() {
        return (ViewLinkImpl) findViewLink("ShoppingCartPaymentOptionViewLink1");
    }

    /**
     * Container's getter for PaymentOptionBillToAddressViewLink1.
     * @return PaymentOptionBillToAddressViewLink1
     */
    public ViewLinkImpl getPaymentOptionBillToAddressViewLink1() {
        return (ViewLinkImpl) findViewLink("PaymentOptionBillToAddressViewLink1");
    }
    public void init(){
        DBTransactionImpl trx= (DBTransactionImpl)getDBTransaction();
        ApplicationModuleImpl am =(ApplicationModuleImpl)trx.getRootApplicationModule();
        String user = am.getUserPrincipalName().toUpperCase();
        System.out.println("The session user is:"+user);
        ViewObjectImpl vo =getShoppingCart1();
        String bindUser = (String)vo.getNamedWhereClauseParam("CurrentUser");
        if(!user.equals(bindUser)){
            vo.setNamedWhereClauseParam("CurrentUser", user);
            vo.executeQuery();
            Row cart=vo.first();
            if (cart==null) {
                       cart = vo.createRow();
                   cart.setAttribute("OrderDate", ((DBTransactionImpl)getDBTransaction()).getCurrentDbTime());
                   cart.setAttribute("OrderStatus", "CART");
                   vo.insertRow(cart);
                   }
        }
        }
}

