package oracle.fod.storefront.module;

import oracle.fod.storefront.entity.OrderEOImpl;
import oracle.fod.storefront.module.common.FODShoppingCartAM;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 16 21:03:37 PST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FODShoppingCartAMImpl extends BaseApplicationModuleImpl implements FODShoppingCartAM {
    /**
     * This is the default constructor (do not remove).
     */
    public FODShoppingCartAMImpl() {
    }

    /**
     * Container's getter for ShoppingCart1.
     * @return ShoppingCart1
     */
    public ViewObjectImpl getShoppingCart1() {
        return (ViewObjectImpl) findViewObject("ShoppingCart1");
    }

    /**
     * Container's getter for ShoppingCartItem1.
     * @return ShoppingCartItem1
     */
    public ViewObjectImpl getShoppingCartItem1() {
        return (ViewObjectImpl) findViewObject("ShoppingCartItem1");
    }

    /**
     * Container's getter for OrderItemsOrdersFkLink1.
     * @return OrderItemsOrdersFkLink1
     */
    public ViewLinkImpl getOrderItemsOrdersFkLink1() {
        return (ViewLinkImpl) findViewLink("OrderItemsOrdersFkLink1");
    }
    public void init(){
        DBTransactionImpl trx= (DBTransactionImpl)getDBTransaction();
        ApplicationModuleImpl am =(ApplicationModuleImpl)trx.getRootApplicationModule();
        String user = am.getUserPrincipalName().toUpperCase();
        System.out.println("The session user is:"+user);
        ViewObjectImpl vo =getShoppingCart1();
        String bindUser = (String)vo.getNamedWhereClauseParam("CurrentUser");
        if(!user.equals(bindUser)){
            vo.setNamedWhereClauseParam("CurrentUser", user);
            vo.executeQuery();
            Row cart=vo.first();
            if (cart==null) {
                       cart = vo.createRow();
                   cart.setAttribute("OrderDate", ((DBTransactionImpl)getDBTransaction()).getCurrentDbTime());
                   cart.setAttribute("OrderStatus", "CART");
                   vo.insertRow(cart);
                   }
        }
        }
    public void addItemToCart(Long productId){
        init();
        ViewObject shoppingCartVO= getShoppingCart1();
        assert shoppingCartVO != null;
        ViewRowImpl shoppingCartRow= (ViewRowImpl)shoppingCartVO.first();
        assert shoppingCartRow!=null;
        OrderEOImpl orderEO = (OrderEOImpl)shoppingCartRow.getEntity(0);
        orderEO.addItemToOrder(productId);
    }
}

