package oracle.fod.storefront.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 18 21:20:40 PST 2015
// ---------------------------------------------------------------------
public interface FODCheckoutAM extends ApplicationModule {
    void init();
}

