package oracle.fod.storefront.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 16 21:57:27 PST 2015
// ---------------------------------------------------------------------
public interface FODShoppingCartAM extends ApplicationModule {
    void addItemToCart(Long productId);

    void init();
}

